spring:
  application:
    name: career-X
  profiles:
    active: local
  ai:
    dashscope:
     api-key: "sk-fcbdc2a8e2184efd957b9c26470ee1f2"
     chat:
       options:
         model: qwen-plus
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b

server:
  port: 8124
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.careerX.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
#自定义日志advisor
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
